# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChallengeSessionUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.answer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.answer_btn.setGeometry(QtCore.QRect(240, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("NovemberPro-Black")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.answer_btn.setFont(font)
        self.answer_btn.setObjectName("answer_btn")
        self.instr_lbl = QtWidgets.QLabel(self.centralwidget)
        self.instr_lbl.setGeometry(QtCore.QRect(30, 50, 351, 31))
        font = QtGui.QFont()
        font.setFamily("NovemberPro-Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.instr_lbl.setFont(font)
        self.instr_lbl.setObjectName("instr_lbl")
        self.question_lbl = QtWidgets.QLabel(self.centralwidget)
        self.question_lbl.setGeometry(QtCore.QRect(30, 90, 351, 31))
        font = QtGui.QFont()
        font.setFamily("NovemberPro-Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.question_lbl.setFont(font)
        self.question_lbl.setObjectName("question_lbl")
        self.answer_field = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_field.setGeometry(QtCore.QRect(22, 160, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(15)
        self.answer_field.setFont(font)
        self.answer_field.setObjectName("answer_field")
        self.heart_1 = QtWidgets.QLabel(self.centralwidget)
        self.heart_1.setGeometry(QtCore.QRect(40, 250, 81, 81))
        self.heart_1.setText("")
        self.heart_1.setPixmap(QtGui.QPixmap("full_heart.png"))
        self.heart_1.setScaledContents(True)
        self.heart_1.setObjectName("heart_1")
        self.heart_2 = QtWidgets.QLabel(self.centralwidget)
        self.heart_2.setGeometry(QtCore.QRect(160, 250, 81, 81))
        self.heart_2.setText("")
        self.heart_2.setPixmap(QtGui.QPixmap("full_heart.png"))
        self.heart_2.setScaledContents(True)
        self.heart_2.setObjectName("heart_2")
        self.heart_3 = QtWidgets.QLabel(self.centralwidget)
        self.heart_3.setGeometry(QtCore.QRect(280, 250, 81, 81))
        self.heart_3.setText("")
        self.heart_3.setPixmap(QtGui.QPixmap("full_heart.png"))
        self.heart_3.setScaledContents(True)
        self.heart_3.setObjectName("heart_3")
        self.score_lbl = QtWidgets.QLabel(self.centralwidget)
        self.score_lbl.setGeometry(QtCore.QRect(100, 350, 231, 31))
        font = QtGui.QFont()
        font.setFamily("NovemberPro-Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.score_lbl.setFont(font)
        self.score_lbl.setObjectName("score_lbl")
        self.finish_btn = QtWidgets.QPushButton(self.centralwidget)
        self.finish_btn.setGeometry(QtCore.QRect(100, 390, 171, 41))
        font = QtGui.QFont()
        font.setFamily("NovemberPro-Black")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.finish_btn.setFont(font)
        self.finish_btn.setObjectName("finish_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.answer_btn.setText(_translate("MainWindow", "Ответить"))
        self.instr_lbl.setText(_translate("MainWindow", "Напишите слово, выделив ударение:"))
        self.question_lbl.setText(_translate("MainWindow", "<МЕСТО_ДЛЯ_СЛОВА>"))
        self.score_lbl.setText(_translate("MainWindow", "Количество очков: 0"))
        self.finish_btn.setText(_translate("MainWindow", "Finish"))
